export const scenario = {
  name: "Parkside Community Events",
  shortName: "parkside",
  tagline: "MORE GOOD DAYS TOGETHER",
  heroTitle: "Find something good nearby.",
  heroDescription: "Join a neighborhood event, check your place, or suggest what we should host next. No account needed.",
  accent: "#627d9b",
  primary: "Join an event",
  primaryDescription: "Pick an event and save your place.",
  primaryIntro: "Choose an event",
  primaryHint: "One event is full. Find an open one below.",
  options: [
    { name: "Saturday garden walk", detail: "Saturday · 10:00 · Riverside Gate", full: true },
    { name: "Neighborhood repair café", detail: "Sunday · 14:00 · Community Hall", full: false },
    { name: "Evening board games", detail: "Tuesday · 18:30 · The Commons", full: false },
  ],
  fullLabel: "Fully booked",
  unavailableError: "That event is full. Choose another one.",
  openLabel: "Places open",
  primaryReview: "Check your place",
  primaryDone: "Your place is saved.",
  referencePrefix: "EV",
  seedReference: "EV-2042",
  seedName: "Neighborhood repair café",
  seedDetail: "Sunday · 14:00 · Community Hall",
  seedStatus: "Place confirmed",
  lookup: "Check a place",
  lookupDescription: "Your demo reference is ready to look up.",
  lookupTitle: "Find your booking",
  lookupHint: "Try the ready-made reference EV-2042.",
  lookupDone: "Here are your booking details.",
  third: "Suggest an event",
  thirdDescription: "Tell us what you would like to do together.",
  thirdTitle: "What should we host?",
  thirdSubject: "Event idea",
  thirdSubjectPlaceholder: "e.g. A weekend nature walk",
  thirdDetails: "What would make it fun?",
  thirdDetailsPlaceholder: "Tell us who it is for and what could happen...",
  thirdDone: "Thanks for the idea.",
  demoNote: "A self-contained demo. Use invented details only.",
} as const;
